IllumiDesk/illumidesk

.travis.yml
.travis/after_success.sh
.travis/script.sh
README.md
dev-requirements.txt

Use the pytest-cov plugin to create coverage report and upload it to codecov.

Create and upload coverage report

---

README.md
ansible/roles/common/tasks/main.yml

- Fix bug where remote docker could not be added to sudoers group.
- Update quickstart in readme.

Update ansible setup instructions

---

README.md

The whitespaces did not do their job

Mark commands with backticks

---

README.md
ansible/group_vars/all.yml
ansible/hosts.example
ansible/roles/jupyterhub/files/share/templates/page.html
ansible/roles/jupyterhub/templates/env.service.j2

Add the correct paths for the `hosts` and `provision.yml` files when running the `ansible-playbook` command with custom vars from the command line.

Update custom ansible-playbook command in Readme

---

.flake8
Makefile
src/illumidesk/apis/jupyterhub_api.py
src/illumidesk/authenticators/authenticator.py
src/illumidesk/authenticators/utils.py
src/illumidesk/authenticators/validator.py
src/illumidesk/spawners/spawner.py
src/setup.py

- Ignore length errors for up to 88 characters
- Update files to remove listing errors

Update flake8 configuration settings

---

.flake8
.pre-commit-config.yaml
.travis/script.sh
CONTRIBUTING.md
Makefile
pyproject.toml
src/illumidesk/apis/jupyterhub_api.py
src/illumidesk/authenticators/authenticator.py
src/illumidesk/authenticators/utils.py
src/illumidesk/authenticators/validator.py
src/illumidesk/spawners/spawner.py
src/setup.py

- Update flake8 settings to explicitly select defaults (E, F, W, C)
- Ignore E231 for certain lines
- Update line length tolerance to get aligned with [django coding style](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/)

Update black and flake8 settings for improved compatibility

---

Makefile
README.md
ansible/group_vars/all.yml
ansible/hosts.example
ansible/provisioning.yml
ansible/roles/jupyterhub/tasks/main.yml
ansible/roles/setup_course/tasks/main.yml

- Update Readme
- Update LTI 11 env var
- Add verbosity option to make deploy command

Update readme and LTI options

---

CHANGELOG.md
package.json

View changelog for release notes.

Release 0.2.0

---

ansible/roles/jupyterhub/templates/docker-compose.yml.j2
ansible/roles/reverse-proxy/tasks/main.yml

traefik service needs this file exist in its startup

Fixes the rules.toml file creation

---

CHANGELOG.md
package.json
src/_version.py

- Update changelog
- Update package and py package versions

Update changelog for release v0.2.3

---

README.md
ansible/group_vars/all.yml
ansible/roles/setup_course/templates/env.setup_course.j2
src/illumidesk/handlers/lms_grades.py
src/illumidesk/setup_course/course.py
tests/illumidesk/setup_course/test_app.py
tests/illumidesk/setup_course/test_course.py

- Add setup-course env vars to readme
- Replace `NFS_ROOT` with `MNT_ROOT`
- Remove `-org-` from grader's image tag

Update mount root environment variable documentation

---

CHANGELOG.md
package.json
src/_version.py

Release 0.3.1

---

CHANGELOG.md
package.json
src/_version.py

Adds text to modal when creating a new assignment within the Grader Console.

Release 0.3.2

---

CHANGELOG.md
package.json
src/_version.py

Circumvents initial course setup when LTI v1.1 or LTI v1.3 is enabled.

Release 0.3.3

---

CHANGELOG.md
package.json
src/_version.py

Patch release to which considers #58

Release 0.3.5

---

ansible/roles/notebooks/files/requirements.txt
ansible/roles/notebooks/templates/Dockerfile.base.j2

- Remove duplicate nbgrader installation
- Adds plotly dependencies
- Refactor dependencies so they are only requirements file
- Add plotly-orca dependency globally with npm
- Remove ipywidget enable command [now that notebook is >=5.3](https://github.com/jupyter-widgets/ipywidgets#install)

Add plotly dependencies

---

CHANGELOG.md
package.json
src/_version.py

- Adds plotly client dependencies to notebook images
- Adds plotly dash server to notebook images

Release 0.4.0

---

.gitignore
package-lock.json
package.json

Commit `package-lock.json` moving forward.

Remove ignore package-lock.json

---

README.md
ansible/roles/setup_course/templates/env.setup_course.j2
src/illumidesk/setup_course/course.py

Rename DOCKER_NETWORK to DOCKER_NETWORK_NAME for all services.

Rename network env var for consistency

---

codecov.yml

Signed-off-by: Greg <werner.greg@gmail.com>

Ignore patch coverages from codecov

---

ansible/roles/jupyterhub/files/jupyterhub_config_fu.py
ansible/roles/jupyterhub/files/requirements.txt

Use the new cull idle server package instead of using the cull idle server file which is slated for removal.

Use cull idle servers package

---

ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
ansible/roles/jupyterhub/templates/Dockerfile.jhub.j2

Add a new cull idle server package to LTI 1.1 configuration.

Update cull idle server configuration to LTI 1.1 config

---

CHANGELOG.md
package-lock.json
package.json
src/_version.py

Adds a Postgres service running as a container for lab/assignment environments.

Release 0.5.0

---

src/illumidesk/tests/illumidesk/authenticators/test_utils.py
src/illumidesk/tests/illumidesk/spawners/test_illumidesk_dockerspawner.py

- verify the use of `{raw_username}` in volumes of dockerspawner class
- verify behavior of `email_to_username` method

Add some unit tests

---

CHANGELOG.md
package-lock.json
package.json
src/_version.py

- Fixes working directory environment variable required for JupyterHub rolling updates
- Register JupyterHub API token with admin privileges using cull-idle service

Release 0.6.1

---

README.md
ansible/hosts.example

Updates customization section with Postgres labs and LTI 1.3 options to enable these additional features.

Documentation updates for Postgres lab and LTI 1.3 customization options

---

CHANGELOG.md
package-lock.json
package.json
src/_version.py

Release v0.7.0

---

ansible/group_vars/all.yml
ansible/roles/notebooks/files/requirements.txt
src/tests/illumidesk/authenticators/test_setup_course_hook.py

Updates Jupyter Notebook base image.

Update base notebook hash commit

---

ansible/group_vars/all.yml

Update JupyterHub hash commit

---

CHANGELOG.md
package-lock.json
package.json
src/_version.py
src/illumidesk/handlers/lti.py

Release v0.7.1

---

CHANGELOG.md
package-lock.json
package.json
src/_version.py

Updates changelog with #132 and #134

Release 0.7.2

---

README.md
ansible/roles/jupyterhub/files/requirements.txt
ansible/roles/notebooks/files/requirements.txt
ansible/roles/notebooks/templates/Dockerfile.base.j2
src/illumidesk/authenticators/authenticator.py
src/illumidesk/authenticators/utils.py
src/tests/illumidesk/authenticators/test_lti11_authenticator.py
src/tests/illumidesk/authenticators/test_utils.py

Clone and merge code located in remote git-based repositories with workspace launches

---

ansible/roles/notebooks/files/requirements.txt

Added FredAPI library to requirements file

Add FredAPI dependency

---

CHANGELOG.md
package-lock.json
package.json
src/_version.py

- Clone git-based repose when launching workspaces
- Adds defaults for demo accounts when deploying with the FirstUseAuthenticator

Release v0.7.3

---

.github/config.yml

Adds welcome messages for new contributors that open issues, open pull requests, and merged pull requests.

Add new welcome messages

---

ansible/ansible.cfg
ansible/hosts.example

Set python interpreter in hosts file

---

ansible/roles/workspaces/notebooks/templates/Dockerfile.base.j2

Add Java apt-get dependencies and Jupyter kernel.
Closes #178

Add java dependencies and jupyter kernel

---

README.md

Add the workspace_type key to the example for Open edX and Canvas LMS.

Update workspaces section with correct key and value example

---

ansible/roles/workspaces/notebooks/templates/Dockerfile.base.j2

Fix java kernel installation

---

ansible/roles/workspaces/theia/files/requirements.txt

Update illumidesk-theia-proxy version

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/_version.py

Improves setup times with the `make deploy` / `ansible-playbook` options.

Release 0.8.1

---

.ansible-lint

Remove trailing ansible-lint config file

---

src/illumidesk/setup_course/constants.py
src/tests/illumidesk/setup_course/test_course.py

Adjust the constant value that is used by the setup-course service to write the nbgrader template when a grader container is launched.
Closes #221

Change the nbgrader template used by the setup_course service

---

.github/workflows/codeql-analysis.yml

Shift left for vulnerability scanning

Add codeql security scanning workflow

---

.github/workflows/stale.yml

Mark issues and PRs as stale after 90 days of inactivity.

Update mark stale issues and pr's action

---

src/illumidesk/setup_course/constants.py

Fix template by adding a escape character in the nbgrader-template

---

README.md

Update defaults to reflect images built with [`illumidesk/docker-stacks`](https://github.com/illumidesk/docker-stacks).

Update notebook environment variables in readme

---

src/illumidesk/authenticators/authenticator.py
src/illumidesk/authenticators/constants.py
src/tests/illumidesk/authenticators/test_lti13_authenticator.py
src/tests/illumidesk/authenticators/test_lti13_validator.py
src/tests/illumidesk/conftest.py

fix: Update required claims and username value when private

---

ansible/roles/illumidesk/tasks/main.yml
ansible/roles/jupyterhub/tasks/main.yml

Update ansible tasks with additional LTI 1.1 conditionals

---

src/illumidesk/apis/nbgrader_service.py
src/illumidesk/authenticators/authenticator.py
src/tests/illumidesk/apis/test_nbgrader_service_helper.py

Make sure to normalize these values in NbGraderServiceHelper class that is responsible to create the assignment and the grader path.

Fix: Normalize the assignment name and course-id

---

ansible/roles/jupyterhub/files/share/templates/405.html
ansible/roles/jupyterhub/files/share/templates/login.html
ansible/roles/jupyterhub/files/share/templates/page.html

- Remove LTI 1.3 button
- Update texts in page templates
This is a temporary update while we migrate all templates and components (js/css) to its own package.

Update template page texts

---

src/illumidesk/apis/nbgrader_service.py
src/tests/illumidesk/apis/test_nbgrader_service_helper.py

Fix source directory permissions

---

src/illumidesk/authenticators/authenticator.py
src/illumidesk/authenticators/constants.py
src/illumidesk/authenticators/utils.py
src/illumidesk/spawners/spawners.py
src/tests/illumidesk/apis/test_announcement_service.py
src/tests/illumidesk/authenticators/test_setup_course_hook.py
src/tests/illumidesk/authenticators/test_utils.py

Include users with TeachingAssistant role in the formgrade group

---

ansible/roles/jupyterhub/files/requirements.txt

Updates `nbgitpuller` from version 0.8.0 to 0.9.0.

Update nbgitpuller version

---

README.md
ansible/roles/jupyterhub/templates/env.jhub.j2
src/illumidesk/authenticators/authenticator.py
src/illumidesk/spawners/spawners.py
src/tests/illumidesk/conftest.py
src/tests/illumidesk/spawners/test_illumidesk_dockerspawner.py

Remove items related with unused grader role

---

src/illumidesk/authenticators/authenticator.py
src/illumidesk/grades/senders.py
src/tests/illumidesk/conftest.py
src/tests/illumidesk/spawners/test_illumidesk_dockerspawner.py

There was an error comparing the assignment name with lineitem label that comes from line_items fetch, now both are normalized

Fix grades submissions with lti13

---

ansible/roles/jupyterhub/files/jupyterhub_config_base.py
src/illumidesk/authenticators/authenticator.py
src/illumidesk/setup_course/course.py
src/illumidesk/spawners/spawners.py
src/tests/illumidesk/spawners/test_illumidesk_dockerspawner.py

- Sets user to root (0)
- Sets NB_UID, NB_GID, NB_USER with spawner's environment option for good measure
This prepares the spawner to use the new base image. illumidesk/docker-stacks#21

Update dockerspawner configuration settings

---

Makefile

Updates makefile to update pip as the first step after creating the virtual environment.

Ensure pip is always up to date

---

src/illumidesk/setup_course/course.py
src/tests/illumidesk/setup_course/test_course.py

Initialize git repo within shared folder:
```git init
git config --local user.name "illumidesk-grader"
git config --local user.email "grader@illumidesk.local"
echo '.ipynb_checkpoints/' >> .gitignore
git add .
git commit -m "Initial commit" 
```

Add git initialization in shared directory

---

README.md
ansible/group_vars/all.yml
ansible/roles/jupyterhub/templates/env.jhub.j2
ansible/roles/setup_course/templates/env.setup_course.j2
ansible/roles/workspaces/tasks/main.yml

Update ansible vars and env vars with new image references

---

ansible/group_vars/all.yml
ansible/hosts.example
ansible/roles/jupyterhub/tasks/main.yml
ansible/roles/jupyterhub/templates/jupyterhub_config_base.py.j2

Add announcement for pilot environments

---

README.md
ansible/group_vars/all.yml
ansible/hosts.example
ansible/roles/jupyterhub/templates/env.jhub.j2
ansible/roles/jupyterhub/templates/jupyterhub_config_base.py.j2

- Updates Reame
- Updates hosts.example with `cpu_limit` setting
- Sets default to `0.5` vCPU
Closes #323

Update CPU limit configuration option

---

README.md
ansible/group_vars/all.yml
ansible/hosts.example
ansible/roles/jupyterhub/templates/env.jhub.j2
ansible/roles/jupyterhub/templates/jupyterhub_config_base.py.j2

- Updates ansible global vars with default setting
- Updates env.jhub with value from env var
- Updates `hosts.example`
- Updates Readme

Add shutdown_on_logout config option

---

README.md
ansible/group_vars/all.yml

Update default workspace image from `illumidesk/full-notebook:latest` to `illumidesk/illumidesk-notebook:latest`.

Update default workspace image

---

.gitignore
src/illumidesk/setup_course/course.py
src/tests/illumidesk/conftest.py
src/tests/illumidesk/setup_course/test_course.py

- Sets the `USER_ROLE` environment variable to `Grader`
Closes #332

Set USER_ROLE for shared grader notebooks

---

ansible/roles/jupyterhub/files/share/templates/page.html

Update the dropdown style to use a fixed length, to show scroll with long list

Improve the grader notebooks dropdown

---

CHANGELOG.md

- Updates changelog with refactor merge from #515

Release version 1.1.0

---

src/grader-service/grader-service/grader_service.py

- Updates `update_jhub_deployment` function to fix `metadata` typo

Fix metadata spelling

---

src/grader-service/grader-service/main.py
src/grader-service/grader-service/models.py
src/illumidesk/illumidesk/apis/setup_course_service.py
src/illumidesk/illumidesk/authenticators/authenticator.py
src/illumidesk/illumidesk/authenticators/constants.py
src/illumidesk/tests/illumidesk/authenticators/test_lti11_authenticator.py
src/illumidesk/tests/illumidesk/authenticators/test_setup_course_hook.py
src/illumidesk/tests/illumidesk/conftest.py

- Moves control file creation to grader setup service
- Update setup_course_hook to call grader set service endpoint to register control file
Closes #525

Refactor control file

---

CONTRIBUTING.md
README.md
src/graderservice/Dockerfile
src/illumidesk/Dockerfile

- Adds Dockerfiles to graderservice and illumidesk folders by copying source files directly using the `COPY` directive
- Updates contribution guide
Closes #563

Add Dockerfiles to graderservice and illumidesk folders

---

CHANGELOG.md
package-lock.json
package.json
src/graderservice/_version.py
src/illumidesk/_version.py

Updates release to version `3.1.0`.

Release v3.1.0

---

CHANGELOG.md
package-lock.json
package.json
src/graderservice/_version.py
src/illumidesk/Dockerfile
src/illumidesk/_version.py

Release v3.2.0

---

CHANGELOG.md
package-lock.json
package.json
src/graderservice/_version.py
src/illumidesk/Dockerfile
src/illumidesk/_version.py

- Fixes incorrect reference for the `wait-for-postgres.sh` script

Fix docker build in the illumidesk context

---

CHANGELOG.md
package-lock.json
package.json
src/graderservice/_version.py
src/illumidesk/_version.py

Release v3.2.1

---

CHANGELOG.md
package-lock.json
package.json
src/graderservice/_version.py
src/illumidesk/_version.py

- Updates release from PRs #578 and #579
- Updates changelog

Release v3.2.2

---

src/illumidesk/Dockerfile
src/illumidesk/illumidesk/apis/nbgrader_service.py
src/illumidesk/illumidesk/authenticators/authenticator.py
src/illumidesk/tests/illumidesk/authenticators/test_lti13_authenticator.py
src/illumidesk/tests/illumidesk/authenticators/test_setup_course_hook.py
src/illumidesk/tests/illumidesk/conftest.py
src/illumideskdummyauthenticator/Dockerfile
src/illumideskdummyauthenticator/README.md
src/illumideskdummyauthenticator/jupyterhub_config.py

Updates the README to include setup instructions for Kubernetes-based environments.
Related to #593

Update readme with kubernetes setup instructions

---

src/graderservice/graderservice/graderservice.py
src/graderservice/tests/conftest.py
src/illumidesk/tests/illumidesk/authenticators/test_lti13_validator.py

Removes dangling print statements.

Remove print statements

---

README.md
src/graderservice/README.md
src/graderservice/graderservice/graderservice.py
src/graderservice/tests/conftest.py
src/illumidesk/README.md
src/illumidesk/illumidesk/apis/nbgrader_service.py
src/illumidesk/illumidesk/apis/setup_course_service.py
src/illumidesk/illumidesk/spawners/hooks.py
src/illumidesk/tests/illumidesk/conftest.py

- Adds option to include requests and limits for both CPU and Memory
- Updates README with new env var settings
Closes #607 #509

Add cpu and mem options for shared grader spawner

---

src/graderservice/README.md
src/graderservice/graderservice/graderservice.py
src/graderservice/tests/conftest.py

Updates the grader notebook pull policy with the Kubernetes Python client
Related to [illumdiesk/helm-chart#152](https://github.com/IllumiDesk/helm-chart/issues/152)

Add grader notebook pull policy

---

src/graderservice/graderservice/templates.py
src/illumidesk/illumidesk/authenticators/authenticator.py

Adds the `await` keyword when adding Students to the JupyterHub `nbgrader-*` group.

Await response when adding students to JupyterHub group
