IllumiDesk/illumidesk

- ansible/roles/illumidesk/templates/lti11-cartridge.xml.j2
Updates the standard launch URL to use `.../hub/lti/launch` for all tool consumers.
Errors were occurring with some tool consumers when initiating launch requests with POST methods, particularly when the XML cartridge link is hosted by a CDN such as CloudFront.
> Update standard launch url for LTI 1.1

- Makefile
- README.md
- ansible/hosts.example
- ansible/roles/common/tasks/main.yml
- Add makefile to consolidate commands for local setup and deployment
- Update Readme with new instructions
> Simplify setup with make and new inventory file

- ansible/roles/jupyterhub/tasks/main.yml
- ansible/roles/jupyterhub/templates/Dockerfile.jhub.j2
This update installs `python 3.8` in JupyterHub's base image. Using python 3.8 will allow us to:
- Move away from Tornado's coroutines and replace them with native async / awaits.
- Using python 3.8 also allows us to use other frameworks within the same package namespace that may require this python version or above.
> Run JupyterHub with Python 3.8

- Makefile
Update `make deploy` command to check for virtual environment, install the virtual environment if it does not exist, and run the setup script with the virtual environment's python bin.
> Update make deploy command for one step setup

- ansible/roles/jupyterhub/templates/Dockerfile.jhub.j2
Add curl to JupyterHub image to correctly display health status with docker container.
> Add curl to jupyterhub

- ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
- src/illumidesk/authenticators/authenticator.py
- src/setup.py
- Remove unused imports from jupyterhub_config
- Remove setup entry point for the authenticator
- Import custom authenticator for LTI 11 with full path
> Update imports and modify authenticator entry point setup

- .pre-commit-config.yaml
- .travis/script.sh
- Makefile
- dev-requirements.txt
There are too many security issues being raised with ansible-lint and its underlying dependencies - removing ansible-lint from the project.
> Remove ansible-lint

- ansible/roles/illumidesk/tasks/main.yml
Ignore `.git`, `*.egg-info` and `build*` folders.
> Rsync ignore 

- ansible/roles/reverse-proxy/tasks/main.yml
Using touch to create the blank `rules.toml` file complicated the permissions setup so moved to use a blank copy instead.
> Create Traefik's rules.toml with copy

- ansible/roles/jupyterhub/files/share/templates/page.html
- Rename 'Services' to 'Grader Notebooks'
- Do not show the 'announcement' service
> Change services menu

- ansible/roles/nbgrader/files/server_extensions/formgrader/static/js/manage_assignments.js
In order to avoid assignment name conflicts when it contains spaces or other characters, we're showing a text to help user in the assignment creation.
> Adds helper text in the assignment creation modal

- README.md
- ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
- ansible/roles/jupyterhub/tasks/main.yml
- ansible/roles/jupyterhub/templates/docker-compose.yml.j2
- ansible/roles/jupyterhub/templates/env.jhub.j2
- remove course definition from docker-compose and jupyterhub_config_lti11.py
- remove user groups
- do not copy the *env.service* file
- remove some vars in env.jhub related to initial course
> Do not use initial course service when LTI is enabled

- ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
- ansible/roles/jupyterhub/templates/env.jhub.j2
- src/illumidesk/handlers/lms_grades.py
- src/setup.py
- tests/illumidesk/handlers/test_lms_grades.py
Replace **pylti** package with **lti** to generate the outcome request. This package contains a class called `OutcomeRequest` that is responsible for create the xml and make the request with all the headers required by Oauth1.0 mechanism but adding the extra `oauth_body_hash` value that moodle is expecting. 
Also Moodle vendor is sending a **json** in `lis_result_sourcedid` field thus the GradesSender  is checking its value to use it correctly.
Finally, the grade score is calculating with Assignment.max_score  value to send number between 1-0. _Maybe we can ilater override some methods in this class to use `resultTotalScore` instead of `resultScore`._
> Fixes grades submission for moodle

- ansible/roles/setup_course/files/Dockerfile
Builds are failing with setup-course image due to the lack of `libxslt-dev` and `g++`.
> Add missing setup-course dependencies

- src/illumidesk/authenticators/authenticator.py
- tests/illumidesk/authenticators/test_lti11_authenticator.py
- tests/illumidesk/authenticators/test_lti11_validator.py
Handle missing lis_outcome_service_url and lis_result_sourcedid arguments with Learner launch requests as well as empty values for when they are included with the launch request.
To replicate:
Initiate a launch request from the Canvas LMS with default values which do not include `lis_*` arguments.
> Handle missing lis arguments with learner launch requests

- requirements.txt
The update to ansible `2.9.10` isn't valid, so reverting to `2.9.9`.
> Revert ansible to 2.9.9

- README.md
- ansible/group_vars/all.yml
- ansible/hosts.hddata
- ansible/roles/jupyterhub/tasks/main.yml
- ansible/roles/jupyterhub/templates/docker-compose.yml.j2
- ansible/roles/notebooks/files/requirements.txt
- add postgres dependency for notebooks
- add new service definition in docker-compose
- add new ansible flag to indicate when to use this service 
How to use with python:
`import psycopg2`
`conn = psycopg2.connect(host="postgres-labs", database="labs", user="postgres", password="postgres")`
> Feature to add a postgres service for labs

- ansible/roles/jupyterhub/files/jupyterhub_config_fu.py
- ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
- ansible/roles/jupyterhub/files/jupyterhub_config_lti13.py
The existing workflow requires using the jupyterhub api token to register new users and users within new and existing groups. This PR adds the jupyterhub api token as an env var to the cull idle service (even though the cull idle service itself is an internally managed service and doesn't need the api token set explicitly).
> Add jupyterhub api token to cull idle service

- README.md
- ansible/hosts.example
- ansible/roles/setup_course/templates/env.setup_course.j2
- src/illumidesk/setup_course/app.py
- src/illumidesk/setup_course/utils.py
- src/illumidesk/tests/conftest.py
- src/illumidesk/tests/illumidesk/setup_course/test_app.py
- src/illumidesk/tests/illumidesk/setup_course/test_course.py
- src/illumidesk/tests/illumidesk/setup_course/test_utils.py
- Handle missing `ILLUMIDESK_DIR` environment variable and set a default value
- Update `hosts.example` to replace the empty value with the default value
- Add basic tests
Closes #83
> Add tests and update docs for missing environment variable used with rolling updates

- ansible/roles/notebooks/files/requirements.txt
Adds `jupyter-dash` and `jupyter-server-proxy` as notebooks dependencies. There are some issues related to accessing the dash when these packages are not installed previously.
> Adds dependencies for plotly dash

- ansible/group_vars/all.yml
Updates Jupyter Notebook image tag based on [git hash commit](https://github.com/jupyter/docker-stacks/commit/76402a27fd13e649a3166b1da5a162ac476912bf).
Closes #123
> Update notebook image tag

- src/illumidesk/handlers/lti.py
- src/tests/illumidesk/handlers/test_lti13_config_handler.py
Modifies the LTI13ConfigHandler to add 'lms_user_id' field in *custom_fields* section: at top level and within course_navigation placement setting.
This adds some unit tests to protect this change.
Closes #117
> Adds lms_user_id in custom_fields

- src/illumidesk/authenticators/authenticator.py
- src/tests/illumidesk/authenticators/test_lti11_authenticator.py
- src/tests/illumidesk/factory.py
Add conditional to LTI 1.1 authenticator to consider the `Student` string when setting the `user_role` key within the `auth_state` dictionary.
Closes #131
> Update conditional in lti11 authenticator with Student string

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- .travis.yml
- CONTRIBUTING.md
- README.md
- SECURITY.md
- codecov.yml
Updates docs to replace `master` branch references to `main` branch references.
> Switch default branch from master to main

- ansible/roles/jupyterhub/files/jupyterhub_config_fu.py
- dev-requirements.txt
- requirements.txt
When setting the orchestrator to use the FirstUseAuthenticator the application would not start unless the `DEMO_` env vars were set. This update adds default values within the configs if the env var is missing or None.
> Add defaults to demo_* env vars

- ansible/roles/common/tasks/main.yml
Install the `nfs-common` package when the playbook is flagged to enable AWS EFS, since it's not always included with Ubuntu distros.
#158
> Install nfs-common required by setups with NFS

- ansible/roles/nbgrader/templates/grader_nbgrader_config.py.j2
The change only affect the **grader_nbgrader_config.py.j2** file that is copied with ansible and used in the docker builds
Closes #180
> Modify the nbgrader config file to include the stub for julia

- ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
- ansible/roles/jupyterhub/files/jupyterhub_config_lti13.py
- src/illumidesk/spawners/hooks.py
- src/illumidesk/spawners/spawners.py
- src/tests/illumidesk/conftest.py
- src/tests/illumidesk/spawners/test_hooks.py
- src/tests/illumidesk/spawners/test_illumidesk_dockerspawner.py
Create a base class with:
- Definition of `start` method to spawn a docker with a specific image (based on the auth_state or the environ)
- Force to use the both hooks (auth_state and pre_spawn) to reduce the logic in the child classes
- Separate the hooks functions
Closes #182
> Refactoring to simplify the logic in spawner classes

- ansible/group_vars/all.yml
- ansible/roles/jupyterhub/templates/Dockerfile.jhub.j2
- ansible/roles/setup_course/files/Dockerfile
- Updates JupyterHub base image to use `jupyterhub/jupyterhub:1.2`
- Updates setup-course image to use the illumidesk custom base images build from the jupyterhub role
Closes #149 
Closes #193
> Update jhub and setup-course base images

- README.md
- ansible/roles/jupyterhub/templates/Dockerfile.jhub.j2
- ansible/roles/setup_course/files/Dockerfile
Add default CMD to the setup-course image to facilitate testing with standard `docker run ...` commands.
Closes #194
> Update setup course service default CMD

- src/illumidesk/authenticators/authenticator.py
Fixes an issue where the course name was not being normalized with LTI 1.3.
> Normalize course label for lti 13

- ansible/roles/jupyterhub/files/requirements.txt
- ansible/roles/setup_course/files/requirements.txt
- ansible/roles/setup_course/tasks/main.yml
- ansible/roles/setup_course/templates/Dockerfile.setup-course.j2
- dev-requirements.txt
- src/setup.py
- Use the standard `python3.8-buster` image as a base image.
- Move pip dependencies to requirements.txt
#129
> Update setup-course microservice to use py3.8

- src/illumidesk/authenticators/authenticator.py
- src/illumidesk/authenticators/utils.py
- src/illumidesk/grades/handlers.py
- src/tests/illumidesk/authenticators/test_lti13_authenticator.py
- src/tests/illumidesk/authenticators/test_setup_course_hook.py
- src/tests/illumidesk/authenticators/test_utils.py
- Change `normalize_name_for_containers` to `normalize_string`
- Move normalize string tasks (username and course id) to setup_course_hook
- Update tests
#198
> Refactor normalize string method

- src/illumidesk/authenticators/authenticator.py
- src/tests/illumidesk/authenticators/test_lti11_authenticator.py
- src/tests/illumidesk/authenticators/test_lti13_authenticator.py
- src/tests/illumidesk/authenticators/test_utils.py
We don't always assign the `setup_course_hook` to the `auth_state_hook`, so it safer to normalize usernames before creating user containers.
#201
> Refactor authenticators to always normalize usernames

- README.md
- ansible/group_vars/all.yml
- ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
- ansible/roles/jupyterhub/files/jupyterhub_config_lti13.py
- src/tests/illumidesk/conftest.py
- Updates LTI configs to use `JUPYTERHUB_ADMIN_USER` instead `JUPYTERHUB_ADMIN_USERS`.
- Replaces `''` with `admin` for default admin user value
- Updated README.md with new setting callout
Closes #218
> Update LTI configs with admin user env var

- src/illumidesk/lti13/handlers.py
- src/tests/illumidesk/lti13/test_lti13_jwks_handler.py
Use tornado's `self.write` method with the python dict (without parse a json) to automatically set *content-type* as json because the LMS does not recognize the response when it is only plain text
Ref: https://www.tornadoweb.org/en/stable/web.html#tornado.web.RequestHandler.write
Closes #204
> Fix the response of /jwks endpoint

- ansible/roles/jupyterhub/files/jupyterhub_config_lti13.py
- src/illumidesk/apis/setup_course_service.py
- src/illumidesk/authenticators/handlers.py
- src/tests/illumidesk/authenticators/test_lti13_handlers.py
With LTI 13 the **next** argument is missing in the login initiation so we have to extract it from `target_link_uri` 
This pr also includes the handler for the `/lti/launch` endpoint to allow receive a launch request from links that were created with lti11 and them need to be upgraded to lti13 version
Closes #214
> Fixes the use of next url with lti13

- src/illumidesk/grades/handlers.py
- src/tests/illumidesk/conftest.py
- src/tests/illumidesk/grades/test_lms_grades_handler.py
When LTI 11Authenticator was used as the authentication type, the SendGradesHandler class ignores the logic to send grades through lti11
> Fix to determine what authenticator is used to submit grades

- src/setup.py
- Update setup.py to reference custom nbgrader
- Adds support for new `lms_lineitems_endpoint`
> Udpate custom nbgrader to version 0.6.2

- README.md
- ansible/group_vars/all.yml
- ansible/hosts.example
- ansible/roles/jupyterhub/files/jupyterhub_config_base.py
- ansible/roles/jupyterhub/templates/env.jhub.j2
- ansible/roles/setup_course/templates/env.setup_course.j2
- src/illumidesk/setup_course/course.py
- src/illumidesk/spawners/spawners.py
- src/setup.py
- src/tests/illumidesk/setup_course/test_course.py
- src/tests/illumidesk/spawners/test_illumidesk_dockerspawner.py
Whit this first approach the setup-course service is creating the "course shared folder" in the path `/<mnt_root>/<org_name>/shared/<course-id>` (with the permissions 10001:100) for the **grader notebooks**.
For the **notebooks case** there is a new volume item in the jupyterhub settings (that applied to all notebooks) that allows to mount the `/<mnt_root>/<org_name>/shared`  in `/home/jovyan/shared`. Notice the host folder termination (/shared ) with this all the future courses will reflected automatically 
Closes #245 
Some screens:
**grader notebook**
**normal notebook**
> Create a shared folder between instructors and students

- README.md
- ansible/group_vars/all.yml
- ansible/hosts.example
- ansible/roles/jupyterhub/files/jupyterhub_config_base.py
- ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
- ansible/roles/jupyterhub/files/jupyterhub_config_lti13.py
- ansible/roles/jupyterhub/templates/env.jhub.j2
- Updates config to redirect users to their servers (JupyterHub.redirect_to_server = True)
- Updates default memory to 2 gigs (Spawner.mem_limit = '2G')
- Adds environment variable to set spawner memory options
> Update default JupyterHub configuration

- src/illumidesk/grades/sender_controlfile.py
- src/tests/illumidesk/authenticators/test_lti11_authenticator.py
- src/tests/illumidesk/grades/test_sender_controlfile.py
For LTI11 when creating the json control file the code assumed the course directory existed but the grader service has not started yet
> Make sure the course directory exists

- README.md
- ansible/wisc-dev.xml
- src/illumidesk/setup_course/constants.py
- Add default header template with `source/header.ipynb`
- Add default footer template with `source/footer.ipynb`
- Update readme
> Add grader header and footer templates

- README.md
- ansible/group_vars/all.yml
- ansible/roles/jupyterhub/files/jupyterhub_config_base.py
- ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
- ansible/roles/jupyterhub/files/jupyterhub_config_lti13.py
- src/illumidesk/apis/jupyterhub_api.py
- src/illumidesk/apis/setup_course_service.py
- src/illumidesk/authenticators/handlers.py
- src/illumidesk/authenticators/utils.py
- src/illumidesk/authenticators/validator.py
- src/illumidesk/grades/handlers.py
- src/illumidesk/lti13/auth.py
- src/illumidesk/lti13/handlers.py
- src/illumidesk/setup_course/app.py
- src/illumidesk/setup_course/course.py
- src/illumidesk/spawners/spawners.py
- src/tests/illumidesk/conftest.py
- src/tests/illumidesk/spawners/test_hooks.py
- src/tests/illumidesk/spawners/test_illumidesk_dockerspawner.py
- Updates spawner to remove logic of spawning user image by LTI role
- Update tests
This update relies on the latest notebook version from `illumidesk/docker-stacks` that enables extensions using the `before-notebook.d` hook based on the user role obtained from the `auth_state`.
> Remove image by role

- ansible/group_vars/all.yml
- Updates jupyterhub base image to use version with python 3.8
- Base image Dockerfile managed in the `illumidesk/helm-chart` repo
> Update jupyterhub base image with py3.8

- ansible/roles/jupyterhub/files/jupyterhub_config_base.py
- src/illumidesk/setup_course/course.py
- src/tests/illumidesk/conftest.py
- Assigns the `DOCKER_END_USER_IMAGE` to the `Spawner.image` configurable
- Assigns the `DOCKER_GRADER_IMAGE` as a `Course` attribute
> Update base spawner config setting with image env var

- src/illumidesk/authenticators/authenticator.py
- src/tests/illumidesk/authenticators/test_lti13_authenticator.py
The auth_state was saving the original value from context label and it affected new methods that use the auth_state dict from the current user.
> Normalize the course-id value before set auth_state

- ansible/hosts.example
Replace `=` with `:` for `shutdown_on_logout` setting.
> Fix typo in hosts.example

- ansible/roles/common/tasks/main.yml
Adds universe source for Ubuntu Focal to remove aptitude installation errors with ansible-playbook setup.
> Add universe for Ubuntu Focal

- src/illumidesk/lti13/handlers.py
Updates the LTI 1.3 configuration endpoint to use the `LtiResourceLinkRequest` instead of the `LtiDeepLinkRequest`.
> Default to resourcelink for assignment placements

- Makefile
- README.md
- ansible/roles/jupyterhub/templates/docker-compose.yml.j2
- ansible/roles/jupyterhub/templates/env.jhub.j2
- ansible/roles/setup_course/templates/env.setup_course.j2
- src/illumidesk/apis/nbgrader_service.py
- src/illumidesk/authenticators/authenticator.py
- src/illumidesk/grades/senders.py
- src/setup.py
- src/tests/illumidesk/apis/test_nbgrader_service_helper.py
- src/tests/illumidesk/conftest.py
The course database will be created with the format: `<org_name>_<course-id>`. 
- The illumidesk **authenticator** class use this database for assignment creation
- Each shared grader service will contain the db_url inside `.jupyter/nbgrader_config.py` file
> Use one database for each course within the organization

- ansible/roles/jupyterhub/templates/docker-compose.yml.j2
- ansible/roles/jupyterhub/templates/env.jhub.j2
- ansible/roles/jupyterhub/templates/jupyterhub_config_base.py.j2
- ansible/roles/setup_course/templates/env.setup_course.j2
- src/tests/illumidesk/apps/test_jupyterhub_base_config.py
- src/tests/illumidesk/conftest.py
- src/tests/illumidesk/lti13/test_lti13_config_handler.py
- Set default usernames / passwords for Postgres containers in docker-compose managed services
- Refactor env vars to avoid duplication
- Cleaner separation of nbgrader, labs, and JupyterHub Postgres services
- Basic tests to check env vars when loading stack
Closes #363
> Refactor postgres container options

- src/illumidesk/spawners/hooks.py
- src/tests/illumidesk/apps/test_jupyterhub_base_config.py
- src/tests/illumidesk/conftest.py
- src/tests/illumidesk/spawners/test_illumidesk_dockerspawner.py
Update the environment variable so that it uses the `NB_NON_GRADER_UID` instead of the `NB_GRADER_UID`.
> Update UID in pre spawn hook to set user folder permissions

- ansible/group_vars/all.yml
This removes potential errors when defining authenticator_class types that are not LTI 1.1.
> Add default values for the LTI 1.1 authenticator

- .github/dependabot.yml
Removes dependabot.yaml to rely solely on dependabot configuration options available within the repo's settings.
> Remove dependabot yaml

- .gitignore
- dev-requirements.in
- dev-requirements.txt
Removes `pytest-kind` dependency. This dependency will be re-enabled once we set up e2e tests with a test Kubernetes cluster using Kind.
> Remove pytest-kind dependency

- src/graderservice/graderservice/graderservice.py
- src/graderservice/graderservice/main.py
- src/graderservice/graderservice/routes.py
- src/graderservice/graderservice/wsgi.py
- src/illumidesk/illumidesk/apis/setup_course_service.py
- Adds the SQLAlchemy rollback() method when encountering an exception
> Rollback commits when encountering an exception

- src/graderservice/graderservice/graderservice.py
- src/graderservice/graderservice/routes.py
- Removes debug option from kubernetes client (python version)
- Test image pushed with `illumidesk/grader-setup-service:revert.2`
Closes #601
> Remove debug option from kubernetes client

- README.md
- src/illumidesk/Dockerfile
- src/illumideskdummyauthenticator/Dockerfile
- src/illumideskdummyauthenticator/README.md
- Updates jupyterhub/jupyterhub base images in Dockerfile to use v1.4.2 by default (version from JupyterHub release)
- Updates jupyterhub/k8s-hub base images in Dockerfile to use v1.1.1 by default (version from helm chart)
- Updates README example to build `illumidesk/k8s-hub` with latest version
Closes #600
> Bump jupyterhub to 1.4.2

- src/graderservice/graderservice/graderservice.py
Removes the int cast for the NB_GID and NB_UID environment variables in the grader service.
This was added when reviewing bug sources for the failing grader-setup-service and finally settled on merging #602, but inadvertently left this cast in place which is not necessary.
> Remove int cast for gid/uid

- Makefile
- README.md
- src/illumidesk/illumidesk/authenticators/authenticator.py
- src/illumidesk/tests/illumidesk/authenticators/test_setup_course_hook.py
- src/illumideskdummyauthenticator/README.md
- src/illumideskdummyauthenticator/illumideskdummyauthenticator/authenticator.py
- src/illumideskdummyauthenticator/illumideskdummyauthenticator/handlers.py
- src/illumideskdummyauthenticator/tests/test_handlers.py
- Replaces the login URL to use `/login` instead of  `/dummy/login`.
- Updates `Makefile` to include commands to build Kubernetes/Docker versions of the JupyterHub
> Change dummy authenticator to use standard login path

- src/graderservice/README.md
- src/graderservice/graderservice/graderservice.py
- Updates the graderservice package to have 2CPU and 4GB as resource limits
- Sets the CPU/Memory limits from env vars
- Renames variables to use the requests and limits vs request and limit for consistency with K8s names
Closes #615
> Update graderservice requests and limits defaults

- Makefile
- src/illumidesk/Dockerfile
- src/illumidesk/illumidesk/authenticators/authenticator.py
- src/illumidesk/tests/illumidesk/authenticators/test_lti13_authenticator.py
- src/illumideskdummyauthenticator/Dockerfile
- Removes the reference to the line item from the LTI 1.3 claim during the authentication flow
- Removes the call to the nbgrader grade book to update the assignment record with the custom line item field (no longer applicable)
- Bumps the Jupyterhub version to 1.4.2 using the helm chart image version 1.1.2
Closes #617
> Fix invalid authentication flow when using line items to identify the assignment

- src/graderservice/graderservice/templates.py
Removes the header and footer templates from the standard `nbgrader_config.py` for shared grader notebooks.
> Remove header and footer settings from config
